sequenceDiagram
    participant browser
    participant server
    participant login page
    participant user
    
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML document
    deactivate server
    

    
    browser->>login page: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate login page
    login page-->>user: login
    deactivate login page
    
    
    user-->>server:GET https://studies.cs.helsinki.fi/exampleapp/main.js
    server-->>user:https://studies.cs.helsinki.fi/exampleapp/data.json 
     user-->>server:[{ "content": "HTML is easy", "date": "2023-1-1" }, ... ]

    activate server
    server-->>browser: 
    deactivate server

    
