sequenceDiagram
    participant browser
    participant server


    browser->>server:get https://studies.cs.helsinki.fi/exampleapp/new note.spa
    server-->>browser:the request was successfully
   
